[package]
name = "chatroom_client"
version = "0.1.0"
edition = "2021"

[dependencies]
im_core = { path = "../../", features = ["client"] }
tokio = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true } 