server:
	RUST_LOG=debug cargo run --example chatroom_server

client:
	RUST_LOG=debug cargo run --example chatroom_client

quic_server:
	RUST_LOG=debug cargo run --example quic_chat server

quic_client:
	RUST_LOG=debug cargo run --example quic_chat client