// This file is @generated by prost-build.
/// 请求消息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// 命令
    #[prost(enumeration = "Command", tag = "1")]
    pub command: i32,
    /// 消息体
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// 客户端消息id
    #[prost(string, tag = "3")]
    pub cient_id: ::prost::alloc::string::String,
}
/// 响应消息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// 设备平台
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Platform {
    Unknown = 0,
    Ios = 1,
    Android = 2,
    Windows = 3,
    /// mac os
    Osx = 4,
    /// 网页
    Web = 5,
    /// 迷你web
    MiniWeb = 6,
    /// Linux设备
    Linux = 7,
    /// 安卓平板
    Apad = 8,
    /// 苹果平板
    Ipad = 9,
}
impl Platform {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Ios => "IOS",
            Self::Android => "ANDROID",
            Self::Windows => "WINDOWS",
            Self::Osx => "OSX",
            Self::Web => "WEB",
            Self::MiniWeb => "MINI_WEB",
            Self::Linux => "LINUX",
            Self::Apad => "APAD",
            Self::Ipad => "IPAD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "IOS" => Some(Self::Ios),
            "ANDROID" => Some(Self::Android),
            "WINDOWS" => Some(Self::Windows),
            "OSX" => Some(Self::Osx),
            "WEB" => Some(Self::Web),
            "MINI_WEB" => Some(Self::MiniWeb),
            "LINUX" => Some(Self::Linux),
            "APAD" => Some(Self::Apad),
            "IPAD" => Some(Self::Ipad),
            _ => None,
        }
    }
}
/// 消息标识符
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Command {
    CmdUnknown = 0,
    /// 系统命令 (1-9)
    ///
    /// ping
    Ping = 1,
    /// pong
    Pong = 2,
    /// 登录
    Login = 3,
    /// 退出登录
    LoginOut = 4,
    /// 设置后台运行
    SetBackground = 5,
    /// 语言设置
    SetLanguage = 6,
    /// 强制用户下线
    KickOnline = 7,
    /// 链接关闭
    Close = 8,
    /// 客户端命令 (10-29)
    ///
    /// 客户端发送消息
    ClientSendMessage = 10,
    /// 客户端拉取消息
    ClientPullMessage = 11,
    /// 客户端发送请求
    ClientRequest = 12,
    /// 客户端确认接收
    ClientAck = 13,
    /// 服务端命令 (30-49)
    ///
    /// 服务端推送消息
    ServerPushMsg = 30,
    /// 服务端推送自定义消息
    ServerPushCustom = 31,
    /// 服务端推送通知
    ServerPushNotice = 32,
    /// 服务端推送数据
    ServerPushData = 33,
    /// 服务端确认接收
    ServerAck = 34,
}
impl Command {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CmdUnknown => "CMD_UNKNOWN",
            Self::Ping => "PING",
            Self::Pong => "PONG",
            Self::Login => "LOGIN",
            Self::LoginOut => "LOGIN_OUT",
            Self::SetBackground => "SET_BACKGROUND",
            Self::SetLanguage => "SET_LANGUAGE",
            Self::KickOnline => "KICK_ONLINE",
            Self::Close => "CLOSE",
            Self::ClientSendMessage => "CLIENT_SEND_MESSAGE",
            Self::ClientPullMessage => "CLIENT_PULL_MESSAGE",
            Self::ClientRequest => "CLIENT_REQUEST",
            Self::ClientAck => "CLIENT_ACK",
            Self::ServerPushMsg => "SERVER_PUSH_MSG",
            Self::ServerPushCustom => "SERVER_PUSH_CUSTOM",
            Self::ServerPushNotice => "SERVER_PUSH_NOTICE",
            Self::ServerPushData => "SERVER_PUSH_DATA",
            Self::ServerAck => "SERVER_ACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CMD_UNKNOWN" => Some(Self::CmdUnknown),
            "PING" => Some(Self::Ping),
            "PONG" => Some(Self::Pong),
            "LOGIN" => Some(Self::Login),
            "LOGIN_OUT" => Some(Self::LoginOut),
            "SET_BACKGROUND" => Some(Self::SetBackground),
            "SET_LANGUAGE" => Some(Self::SetLanguage),
            "KICK_ONLINE" => Some(Self::KickOnline),
            "CLOSE" => Some(Self::Close),
            "CLIENT_SEND_MESSAGE" => Some(Self::ClientSendMessage),
            "CLIENT_PULL_MESSAGE" => Some(Self::ClientPullMessage),
            "CLIENT_REQUEST" => Some(Self::ClientRequest),
            "CLIENT_ACK" => Some(Self::ClientAck),
            "SERVER_PUSH_MSG" => Some(Self::ServerPushMsg),
            "SERVER_PUSH_CUSTOM" => Some(Self::ServerPushCustom),
            "SERVER_PUSH_NOTICE" => Some(Self::ServerPushNotice),
            "SERVER_PUSH_DATA" => Some(Self::ServerPushData),
            "SERVER_ACK" => Some(Self::ServerAck),
            _ => None,
        }
    }
}
/// 消息响应码
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResCode {
    /// 成功
    Success = 0,
    /// 消息内容解码错误
    DecodeErr = 1,
    /// 消息内容编码错误
    EncodeErr = 2,
    /// 参数错
    ArgsErr = 3,
    /// 找不到处理方法
    NotFoundHandler = 4,
    /// 消息发送失败
    InternalServiceErr = 5,
    /// 发送失败
    SendErr = 6,
    /// 业务错误
    BusinessErr = 7,
    /// 连接错误
    ConnectionError = 8,
    /// 无效命令
    InvalidCommand = 9,
    /// 未授权
    Unauthorized = 10,
}
impl ResCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Success => "SUCCESS",
            Self::DecodeErr => "DECODE_ERR",
            Self::EncodeErr => "ENCODE_ERR",
            Self::ArgsErr => "ARGS_ERR",
            Self::NotFoundHandler => "NOT_FOUND_HANDLER",
            Self::InternalServiceErr => "INTERNAL_SERVICE_ERR",
            Self::SendErr => "SEND_ERR",
            Self::BusinessErr => "BUSINESS_ERR",
            Self::ConnectionError => "CONNECTION_ERROR",
            Self::InvalidCommand => "INVALID_COMMAND",
            Self::Unauthorized => "UNAUTHORIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCESS" => Some(Self::Success),
            "DECODE_ERR" => Some(Self::DecodeErr),
            "ENCODE_ERR" => Some(Self::EncodeErr),
            "ARGS_ERR" => Some(Self::ArgsErr),
            "NOT_FOUND_HANDLER" => Some(Self::NotFoundHandler),
            "INTERNAL_SERVICE_ERR" => Some(Self::InternalServiceErr),
            "SEND_ERR" => Some(Self::SendErr),
            "BUSINESS_ERR" => Some(Self::BusinessErr),
            "CONNECTION_ERROR" => Some(Self::ConnectionError),
            "INVALID_COMMAND" => Some(Self::InvalidCommand),
            "UNAUTHORIZED" => Some(Self::Unauthorized),
            _ => None,
        }
    }
}
