services:
  consul:
    image: consul:1.15
    container_name: flare-consul
    ports:
      - "8500:8500"  # HTTP API & UI
      - "8600:8600/udp"  # DNS Interface
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul-data:/consul/data
    networks:
      - flare-net

  etcd:
    image: bitnami/etcd:3.5
    container_name: flare-etcd
    ports:
      - "2379:2379"  # Client API
      - "2380:2380"  # Peer API
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/bitnami/etcd
    networks:
      - flare-net

networks:
  flare-net:
    driver: bridge

volumes:
  consul-data:
  etcd-data: 