[package]
name = "rpc_core"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-broadcast = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
etcd-client = {workspace = true}
uuid = { workspace = true}
tonic = { workspace = true }
rand = { workspace = true}
prost = {workspace = true}

[build-dependencies]
tonic-build = { workspace = true }